### ISSUE TITLE
Update metadata.json

### ISSUE THREAD

**Issue by razorsedge** [deadpoint/puppet-zypprepo#6]
Puppet now depends on the metadata.json file storing all the relevant details from the Modulefile.  If you have a minute, could you run`puppet module build` commit a new version of the file?

**Comment by deadpoint** [comment]
metadata.json updated and published to the forge as version 1.0.2. No other changes have been made to the module.

**Comment by razorsedge** [comment]
@deadpoint Could you also commit the metadata.json to this git repository?  I was not clear, but that was my need.

**Comment by deadpoint** [comment]
done

--
Later,
Darin
